---
layout: cv
title: Ethan Saline's CV
---
# Ethan Saline
Data Science Student

<div id="webaddress">
<a href="www.linkedin.com/in/ethan-saline">Linkedin</a>
| <a href="https://github.com/Ethan-Saline/Ethan_Saline_Portfolio.git">Github</a>
</div>

## SKILLS
Machine Learning: Tensorflow, Optimizing Models, Pipelining
Data Science: Pandas, NumPy, SciPy
Data Visualization: GGPlot, Matplotlib, Seaborn
Big Data & Databases: MySQL, SQLite
Spoken Languages: Portuguese (Fluent), English (Native)
Other: JIRA, CI/CD

## EXPERIENCE
BYUI Math/Data Science Lab - Tutor
SEPTEMBER 2024 - PRESENT
Assisted students in developing problem-solving skills and mathematical reasoning focused in Calculus
Church of Jesus Christ of Latter-Day Saints, São Paulo - Missionary
OCTOBER 2021 - OCTOBER 2023
Developed fluency in Portuguese and cross-cultural communication skills.

## EDUCATION
Brigham Young University Idaho - Data Science Major, Statistics Minor
APRIL 2024 - OCTOBER 2026

## CERTIFICATIONS
Brigham Young University Idaho, OCTOBER 2026
Machine Learning

Stanford University, FEBRUARY 2024
Machine Learning
Advanced Learning Algorithms
Unsupervised Learning, Recommenders, Reinforcement Learning
Supervised Machine Learning: Regression and Classification 
